FROM ubuntu:22.04

LABEL maintainer="Stephan Kantelberg <stephan.kantelberg@zuehlke.com>"

ARG DEB_COMPILERS="g++-{{ gcc | join(' g++-') }}"
ARG EXTRA_CLANG_COMPILERS="{{ clang.keys() | join(' ') }}"

EXPOSE 10240

RUN echo "*** Installing compiler required packages ***" \
    && export DEBIAN_FRONTEND=noninteractive  \
    && apt-get update \
    && apt-get install -y \
       wget \
       gnupg2 \
       lsb-release \
       apt-utils \
       ninja-build \
       software-properties-common

ADD scripts/install_compilers.sh /install_compilers.sh
ADD scripts/install_libraries.py /install_libraries.py

RUN echo "*** Installing C++ Compilers ***" \
    && chmod +x /install_compilers.sh \
    && sh /install_compilers.sh "${DEB_COMPILERS}" "${EXTRA_CLANG_COMPILERS}"


RUN echo "*** Installing Compiler Explorer ***" \
    && DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y \
       ca-certificates \
       nodejs \
       make \
       gcc \
       g++ \
       git \
       python3 \
    && apt-get autoremove --purge -y \
    && apt-get autoclean -y \
    && rm -rf /var/cache/apt/* /tmp/* \
    && git clone https://github.com/compiler-explorer/compiler-explorer.git /compiler-explorer \
    && cd /compiler-explorer \
    && echo "Add missing dependencies" \
    && npm i @sentry/node \
    && npm run webpack

{% if 'cmake' in tools.keys() %}
RUN mkdir -p /tools/cmake && cd /tools/cmake \
    && wget https://github.com/Kitware/CMake/releases/download/v{{ tools.cmake }}/cmake-{{ tools.cmake }}-linux-x86_64.sh  \
    && chmod +x cmake-{{ tools.cmake }}-linux-x86_64.sh  \
    && ./cmake-{{ tools.cmake }}-linux-x86_64.sh --include-subdir --skip-license \
    && rm cmake-{{ tools.cmake }}-linux-x86_64.sh
ENV PATH="${PATH}:/tools/cmake/cmake-{{ tools.cmake }}-linux-x86_64/bin/:"
{%- endif %}

RUN echo "*** Install libs ***" \
    {%- for lib in libraries %}
    && echo "Installing {{ lib }}" \
    && python3 /install_libraries.py {% if libraries[lib].staticliblink %} -i {% endif %} -n {{ lib }} -u {{ libraries[lib].url }} -v {{ libraries[lib].versions | join(' ') }} \
    {%- endfor %}
    && echo "Libraries installed!"

{% for tool, version in tools.items() %}
{%- if 'iwyu' == tool %}
RUN mkdir iwyu && cd iwyu \
    && apt install libclang-{{ version }}-dev \
    && git clone --branch clang_{{ version }} https://github.com/include-what-you-use/include-what-you-use.git \
    && mkdir build && cd build \
    && cmake -G "Ninja" -DCMAKE_PREFIX_PATH=/usr/lib/llvm-{{ version }} ../include-what-you-use \
    && ninja install \
    && cd ../.. \
    && rm -rf iwyu
{%- endif %}
{%- endfor %}

ADD generated/cpp.properties /compiler-explorer/etc/config/c++.local.properties

WORKDIR /compiler-explorer

ENTRYPOINT [ "make" ]

CMD ["run"]
