name: Docker Build Compiler Explorer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install conan
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        source ~/.profile
    - name: Generate files
      run: python3 scripts/generator.py
    - name: Build Dockerfile
      run: docker build . --file generated/Dockerfile -t docker-compiler-explorer
